import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./(site)/globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { auth } from "@/auth";
import { Toaster } from "react-hot-toast";
import { EdgeStoreProvider } from "../libs/edgestore";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Nextjs BlogX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();


  return (
    <html lang='en'>
      <body className={`overflow-x-hidden bg-light ${roboto.className}`}>
        <EdgeStoreProvider>
          <Navbar session={session} />
          <Toaster />
          {children}
          <Footer />
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
